site_name: gitlab-releases
repo_url: https://github.com/valbertovc/gitlab-releases

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - python
        - bash

nav:
  - gitlab-releases: index.md
  - Get Started: get-started.md
  - How To Customize: how-to-customize.md

plugins:
  - tags