name: Check code
on:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: astral-sh/ruff-action@v3
      - run: |
          ruff check
          ruff format

  test:
    needs: code-quality
    name: test ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.13"
          - "3.9"
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - run: |
          pip install -U pip
          pip install tox
      - run: tox

  coverage:
    needs: test
    name: Check coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install coverage[toml]
      - name: Run test suite with coverage
        run: |
          pip install -U pip
          pip install Django coverage
          coverage run manage.py test
          coverage report
          coverage xml
      - name: Code coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}