name: Check code
on:
  pull_request:

jobs:
  
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - run: |
          pip install -U pip
          pip install ruff isort
      - run: ruff . --check

  test:
    needs: code-quality
    name: test ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.13"
          - "3.9"
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - run: |
          pip install -U pip
          pip install tox
      - run: tox

  test-pypi:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Build
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.7"
      - name: Test publish
        env:
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi $TEST_PYPI_TOKEN
          poetry publish --build --dry-run --repository test-pypi

  coverage:
    needs: test
    name: Check coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install coverage[toml]
      - name: Run test suite with coverage
        run: |
          pip install -U pip
          pip install Django coverage
          coverage run manage.py test
          coverage report
          coverage xml
      - name: Code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}